### ISSUE TITLE
mudar todo css para styled components ou usar uma biblioteca parecida com bootstrap?

### ISSUE THREAD

**Issue by felipepassosdev** [felipepassosdev/devhipster#7]

**Comment by Wilgnne** [comment]
Os componentes serão reescritos do zero com styled components ou utilizará alguma biblioteca como [bootstrap-styled](https://bootstrap-styled.github.io/bootstrap-styled/) ?

**Comment by leogaletti** [comment]
Verdade, bom saber pra termos um padrão a seguir. Dai podemos dividir as telas e começar o trabalho!

**Comment by leogaletti** [comment]
Podemos usar também o [React-Bootstrap](https://react-bootstrap.github.io/)

**Comment by felipepassosdev** [comment]
Cara, conheci essa biblioteca ontem, ainda não sei se vale a pena usar, estamos ai para sugestões

**Comment by felipepassosdev** [comment]
O que pensei é usar alguma biblioteca que cuidasse da parte visual, pra gente perder mais tempo com a parte de usabilidade no começo

**Comment by Wilgnne** [comment]
Acredito então que o [React Bootstrap](https://react-bootstrap.github.io/) seja uma boa opção, como bem apresentado pelo @leogaletti

**Comment by felipepassosdev** [comment]
Eu acho uma ótima ideia, alguém se habilita a essa tarefa?

**Comment by Wilgnne** [comment]
Me habilito a realizar esta migração

**Comment by felipepassosdev** [comment]
Combinado

**Comment by Wilgnne** [comment]
Até o momento as páginas Home, JavaScript e o NavBar foram convertidos para React Bootstrap

**Comment by Wilgnne** [comment]
Acabo de espelhar o fix do GlobalStyle que o @felipepassosdev implementou e o resultado é este
![Capturar](https://user-images.githubusercontent.com/38788330/82269436-10657100-9948-11ea-8660-bbdbc2d6590b.PNG)
e o codigo ficou bastante elegante,
```javascript
function Home() {
  return (
    <Container>
      <div className='p-5'></div>
      <Row>
        {courses.map((course, index) =>
          <CardCourse
            key={index}
            title={course.title}
            description={course.description}
            icon={course.icon}
            color={course.color}
            url={course.url}
          />
        )}
      </Row>
    </Container>
  );
}
```
com os cards de curso extraidos para um novo componentes customizavel
```javascript
function CardCourse({ title, description, icon, url, color }) {

  const history = useHistory();

  function handleClick() {
    history.push(url);
  }

  return (
    <Col md='4' style={{ padding: '15px' }} >
      <Card className={['dark', color, 'shadow'].join(' ')} bg="dark" text="white">
        <Card.Body className="text-white">
          <Card.Title className={color}>
            <h3>{title}</h3>
          </Card.Title>
          <Image fluid={true} src={icon} />
          <h5>{description}</h5>
          <Button
            onClick={handleClick}
            variant='dark'
          >
            <h5 style={{ margin: 0 }} >EM BREVE</h5>
          </Button>
        </Card.Body>
      </Card>
    </Col>
  );
}
```
o resultado me agrada bastante, gostaria de saber a opnião dos demais.

**Comment by felipepassosdev** [comment]
Parabéns, ficou muito bom, já está disponível ;)
